site:
  title: The Loft at 600F
  domain: localhost:3000
  brand: /img/meeting-space-logo.png
  protocol: http
  typekit:
    id: sue6sls
  css:
    - href: /css/style.css
  js:
    - href: /vendor/jquery-1.8.3.min.js
    - href: /js/parallax.js
    - href: /js/header.js
  sections:
    -
      name: about
      title: About
      header: false
      tagline: "The Loft at 600 F is a vibrant, exciting, and inviting event space in the Penn Quarter/Chinatown neighborhood of Washington DC."
      image: /img/loft-table.jpg
      caption: "A fully set table at the Loft"
      body: "Perched on the third floor of a historic building across from the Verizon Center, the light-filled, modern space can be set in various layouts ranging from a comfy lounge to a formal conference table or from a engaging lecture to an inviting happy hour. <br> Chic furnishings and exposed brick are accented with modern technology in the perfect downtown location making The Loft at 600 F the best new place to meet in DC."
    -
      name: the-space
      title: The Space
      header: true
      header_image: /img/meeting-image-2.jpg
      body:
        -
          image: /img/floor-plan-meeting.png
          caption: "<strong>Total Square Footage:</strong> approximately 1,000 square feet"
          plain_caption: "Total Square Footage: approximately 1,000 square feet"
        -
          copy: "The Loft at 600 F is a versatile space, available for whatever your event needs may be. The light-filled, modern space can be set in various layouts ranging from a comfy lounge to a formal conference table or from a engaging lecture to an inviting happy hour. <br>Perfect for happy hours, networking events, book signings, meet-and-greets, as a pre- or after party lounge and so much more. Exposed brick, large windows and cozy modern touches distinguish this space as the hip new place to meet."
          equipment:
            title: Furniture/Equipment <span class="note">*</span>
            list:
              - text: "Custom sofas, available in various setups"
              - text: "Movable bars"
              - text: "Cofee table, site tables, and credenzas"
              - text: "Up-lighting and accent lighting"
              - text: "Highboy round tables"
              - text: "6' X 15' Classroom tables and black rectangular linens"
              - text: "Standing podium"
              - text: "Easels"
              - text: "Coat racks"
              - text: "Folding chairs"
              - text: "Microwave, kitchen sink, and mini-fridge"
          av:
            title: A/V Capabilities
            list:
              - text: "HD projector"
              - text: "HDMI"
              - text: "10' widescreen projection screen"
              - text: "Surround sound receiver"
              - text: "BluRay player"
              - text: "Mac Mini"
              - text: '55" HD television'
              - text: "WiFi"
          note: <span class="note">*</span>Furniture and equipment listed are complimentary with all Loft reservations.

    -
      name: events
      title: Events
      header: true
      header_image: /img/meeting-image-3.jpg
      body:
        -
          title: Types of Events
          copy: "The Loft at 600 F is a multi-purpose space that can be set to accomodate events of all kinds, including:"
          events:
            - text: "Corporate meetings and conferences"
            - text: "Birthday parties"
            - text: "Weddings"
            - text: "Engagement parties, bridal showers, and baby showers"
            - text: "Pop-ups for retail, art galleries, or group classes"
            - text: "Fundraisers"
            - text: "Happy hours"
            - text: "Screenings"
            - text: "Book signings"
            - text: "Photo shoots"
            - text: "Holiday events"
          image: /img/loft-food.jpg
          caption: Loft food
        -
          title: Catering
          copy: "The loft at 600F allows outside catering of all kinds. Our preferred vendors appear below, but other vendors may provide service on-site with proof of insurance.<br>Clients are required to hire an ABC licensed bartender (or full-service caterer) if alcohol will be served at their event. <i>Proof of licensing and insurance is required</i>."
          caterers:
            -
              logo: img/logo-ridgewells.png
              url: "#"
              title: "Ridgewells"
              address1: "5525 Dorsey Lane"
              address2: "Bethesda, MD 20816"
              phone: "301.907.3712"
              fax: "301.907.3733"
              email: "tmoyher@ridewells.com"
            -
              logo: img/logo-mainevent.png
              url: "#"
              title: "Main Event Caterers"
              address1: "3870 S. Four Mile Run Drive"
              address2: "Arlington, VA 22206"
              phone: "703.820.2028 x223"
              fax: "703.820.2054"
            -
              logo: img/logo-rkristi.png
              url: "#"
              title: "R. Kristi Modern Hospitality"
              address1: "8775 Cloudleap Court"
              address2: "Arlington, VA 22206"
              phone: "1-888-RKRISTI (757-4784)"
              email: "info@bykristi.com"
            -
              logo: img/logo-rr.jpg
              url: "#"
              title: "R & R Catering"
              address1: "8004 Alban Road"
              address2: "Springfield, VA 22150"
              phone: "703.451.2798 x223"
              fax: "703.451.4380"
    -
      name: gallery
      title: Gallery
    -
      name: contact-us
      title: Contact
      header: true
      header_image: /img/meeting-image-4.jpg
      body:
        -
          contact: Dan Lovato
          title: "Venue & Events Manager"
          phone: "202.431.8516"
          email: "info@TheLoftat600F.com"
        -
          image: /img/600f.jpg
        -
          contact: The Loft at 600 F
          address1: 600 F Street NW
          address2: Suite 300
          address3: "Washington, DC 20004"
network:
  domain: localhost
log:
  trace: true
  req:
    enable: true
flickrOptions:
  key: 0c07b11313acc6e708c7e5360b6d61ef
  secret: ec34b66f5a1b0c4d
  user_id: 126110510@N03
  access_token: 72157645676835476-fe5e507cc7ce76e9
  access_token_secret: 774ba626f4e5ebd3
